site_name: Studio P4 Documentation
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."] # Tells the parser to look in your root folder for 'core' and 'ui'

nav:
  - Home: index.md
  - Musician's Guide: 
      - Recording a Loop: recording_loop.md
      - Managing Tracks & Sounds: managing_tracks.md
      - Saving & Loading: saving_projects.md
      - Configuring the Voice: voice_config.md
  - Developer's Guide:
      - System Setup: setup.md
      - Remapping MIDI Controls: remap_midi.md
      - Adding SoundFonts: add_soundfonts.md
      - Building the EXE: build_exe.md
  - Architecture & Concepts: 
      - Accessibility Philosophy: accessibility_philosophy.md
      - System Architecture: architecture.md
      - Data Flow Pipelines: data_flow.md
  - API Reference:
      - Controllers & MIDI: api.md
      - Audio Engine: engine.md
      - Data Models: models.md
      - User Interface: ui.md