name: Deploy MkDocs

# This tells the robot to run every time you push to the 'main' branch
on:
  push:
    branches:
      - main 

# Gives the robot permission to push the website files back to GitHub
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install mkdocs-material mkdocstrings[python]
        
      - name: Build and Publish
        run: mkdocs gh-deploy --force